# Generated by Django 4.0 on 2024-01-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='phone',
        ),
    ]
